# Generated by Django 3.1.7 on 2022-02-09 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
        ('store', '0002_auto_20220123_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='fkk',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='customer.shop_user'),
        ),
    ]
