# Generated by Django 3.1.7 on 2022-02-10 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20220209_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='pincode',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
