# Generated by Django 3.1.7 on 2022-02-26 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_customer_pincode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='shop',
        ),
    ]
