# Generated by Django 3.1.7 on 2022-04-18 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_remove_products_fkk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shop',
        ),
        migrations.AddField(
            model_name='order',
            name='shopss',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
