# Generated by Django 3.1.7 on 2022-04-18 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop_user',
            name='district',
        ),
    ]
