# Generated by Django 3.1.7 on 2022-04-22 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='ml',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Month', models.DateField()),
                ('Sales', models.IntegerField()),
            ],
        ),
    ]
