# Generated by Django 3.1.7 on 2022-04-25 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snum', models.CharField(default='', max_length=20)),
                ('image', models.ImageField(blank=True, upload_to='')),
            ],
        ),
    ]
