# Generated by Django 3.1.7 on 2022-04-25 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_component_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='snum',
            field=models.CharField(default='n', max_length=20),
        ),
    ]
